# Generated by Django 4.0.5 on 2022-09-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmain', '0002_category_product_photo_product_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
