# Generated by Django 4.0.5 on 2022-09-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmain', '0003_category_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo/%Y/%m/%d/'),
        ),
    ]
