# Generated by Django 4.0.5 on 2022-09-16 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopmain', '0004_alter_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo',
        ),
    ]
