# Generated by Django 4.0.5 on 2022-09-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopmain', '0005_remove_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
